default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host:     <%= ENV['POSTGRES_HOST'] %>
  port:     <%= ENV['POSTGRES_PORT'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: manager_app_development

test:
  <<: *default
  database: manager_app_test

production:
  <<: *default
  database: manager_app_production
