version: '3'

networks:
  homework_kafka-net:
    external: true
  contractor-app:
    driver: bridge

services:
  contractor_app:
    image: pilot/contractor_app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server --port 3000 --binding '0.0.0.0'"
    ports:
      - 3333:3000
    volumes:
      - .:/app
      - contractor_app_gem_cache:/gems
    depends_on:
      - contractor_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=contractor_postgres
      - POSTGRES_PORT=5432
      - KAFKA_HOST=kafka:9092
      - KAFKA_CLIENT_ID=contractor_app
    networks:
      - homework_kafka-net
      - contractor-app

  contractor_postgres:
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - contractor-app
    volumes:
      - contractor_postgres:/var/lib/postgresql/data

volumes:
  contractor_app_gem_cache:
  contractor_postgres:
