version: '3'

networks:
  homework_kafka-net:
    external: true
  manager-app:
    driver: bridge

services:
  manager_app:
    image: pilot/manager_app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server --port 3000 --binding '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - manager_app_gem_cache:/gems
    depends_on:
      - manager_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=manager_postgres
      - POSTGRES_PORT=5432
      - KAFKA_HOST=kafka:9092
      - KAFKA_CLIENT_ID=manager_app
    networks:
      - homework_kafka-net
      - manager-app

  manager_karafka:
    image: pilot/manager_app
    command: /bin/sh -c "bundle exec karafka server"
    volumes:
      - .:/app
      - manager_app_gem_cache:/gems
    depends_on:
      - manager_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=manager_postgres
      - POSTGRES_PORT=5432
      - KAFKA_HOST=kafka:9092
      - KAFKA_CLIENT_ID=manager_app
    networks:
      - homework_kafka-net
      - manager-app

  manager_postgres:
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - manager-app
    volumes:
      - manager_postgres:/var/lib/postgresql/data

volumes:
  manager_app_gem_cache:
  manager_postgres:
